export const saskKeywords = [
  // Generic sask keywords
  'sask',
  'saskatchewan',
  'saskatoon',
  'regina',
  'saskatchewanians',
  'saskatchewanian',
  'sk',
  'regina',
  'yxe',
  'yqr',
  'skpoli',
  'bunny hug',
  'bunnyhug',
  'bunny-hug',
  'land of the living skies',
  'western canada',
  'prairie',
  'prairie province',
  'prairie provinces',

  // Saskatchewan towns, cities, places, etc
  'aberdeen',
  'allan',
  'alvena',
  'arcola',
  'ashville',
  'assiniboia',
  'avonlea',
  'balcarres',
  'bengough',
  'biggar',
  'birsay',
  'borden',
  'broadview',
  'bulyea',
  'canora',
  'carievale',
  'carlyle',
  'carnduff',
  'caronport',
  'central butte',
  'churchbridge',
  'colonsay',
  'coronach',
  'creelman',
  'creighton',
  'cupar',
  'cut knife',
  'dalmeny',
  'davidson',
  'delisle',
  'duck lake',
  'eastend',
  'edenwold',
  'edam',
  'elrose',
  'estevan',
  'esterhazy',
  'eston',
  'foam lake',
  'fort quappelle',
  'fort san',
  'foxberry',
  'flin flon',
  'gravelbourg',
  'warman',
  'martensville',
  'yorkton',
  'moose jaw',
  'swift current',
  'prince albert',
  'north battleford',
  'melfort',
  'melville',
  'wadena',
  'wakaw',
  'la ronge',
  'uranium city',
  'la loche',
  'medstead',
  'meadow lake',
  'kindersley',
  'estevan',
  'weyburn',
  'humboldt',
  'foam lake',
  'glaslyn',
  'lloydminster',
  'lloyd',
  'spiritwood',
  'tisdale',
  'nipawin',
  'carrot river',
  'goodsoil',
  'canora',
  'kamsack',
  'big river',
  'shellbrook',
  'turtleford',
  'macklin',

  // Saskatchewan universities, colleges, schools, etc
  'usask',

  // Saskatchewan sports teams
  'roughriders',

  // Saskatchewan people
  'diefenbaker',
  'tommy douglas',
  'gordie howe',
  'jon ryan',
  'bret hart',
  'bret the hitman hart',
  'wendel clark',
  'leslie nielsen',
  'buffy sainte-marie',
  'sandra schmirler',
  'allen sapp',
]